# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - dashboards
  - deploy.yml
  - sm.yml
  - rbac.yml


images:
  - name: alpine
    newName: registry.sighup.io/sighupio/fury/alpine
  - name: quay.io/prometheus/node-exporter
    newName: registry.sighup.io/sighupio/fury/prometheus/node-exporter
  - name: quay.io/coreos/kube-rbac-proxy
    newName: registry.sighup.io/sighupio/fury/coreos/kube-rbac-proxy