apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: http-metrics
    relabelings:
    - action: labeldrop
      regex: (pod|service|endpoint|namespace)
    scrapeTimeout: 30s
  - interval: 30s
    port: telemetry
  jobLabel: app
  selector:
    matchLabels:
      app: kube-state-metrics
