---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: copper
    group: test
    image: ruby:2.5
    commands:
      - gem install c66-copper && copper version
      - apt-get update && apt-get install curl -y
      - curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.10/kustomize_1.0.10_linux_amd64 -o /usr/local/bin/kustomize && chmod +x /usr/local/bin/kustomize && kustomize version
      - ls test
      - bash test/copper.sh
    when:
      event:
      - push
  - name: prom-rules
    group: test
    image: alpine:3.8
    commands:
      - apk add ca-certificates curl bash --no-cache --update
      - curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/2.2.0/yq_linux_amd64 && chmod +x /usr/local/bin/yq
      - curl -O -L  https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.linux-amd64.tar.gz && tar -xzvf prometheus-2.5.0.linux-amd64.tar.gz && chmod +x prometheus-2.5.0.linux-amd64/promtool && mv prometheus-2.5.0.linux-amd64/promtool /usr/local/bin/promtool && promtool --version
      - bash test/promtool.sh
    when:
      event:
      - push

  - name: integration-test
    image: sighup/kind:v1.12.3
    environment:
      CLUSTER_HOST: docker
    commands:
      - sh test prometheus-operator kube-state-metrics node-exporter alertmanager-operated grafana kubeadm-sm prometheus-operated
    volumes:
      - name: dockersock
        path: /var/run
    when:
      event:
      - push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
