---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:

  - name: katalog
    image: sighup/katalog:v1.0.11
    group: tests
    pull: always
    commands:
      - flake8 --ignore=E501 katalog/tests/test.py
      - bash katalog/tests/pytest.sh
      - rm -rf .pytest_cache katalog/tests/__pycache__
    when:
      event:
      - push

  - name: prom-rules
    image: sighup/prom-rules:v1.0.0
    pull: always
    commands:
      - bash katalog/tests/promtool.sh
    when:
      event:
      - push

  - name: integration-test
    image: sighup/kind:v1.12.3-bats
    pull: always
    environment:
      CLUSTER_HOST: docker
      DIRS: prometheus-operator kube-state-metrics node-exporter alertmanager-operated grafana kubeadm-sm prometheus-operated
    volumes:
      - name: dockersock
        path: /var/run
    when:
      event:
      - push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
