---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: katalog
    image: quay.io/sighup/katalog:1.0.10_3
    pull: always
    depends_on: [ clone ]
    commands:
      - flake8 --ignore=E501 katalog/tests/test.py
      - bash katalog/tests/pytest.sh
      - rm -rf .pytest_cache katalog/tests/__pycache__
    when:
      event:
      - push

  - name: prom-rules
    image: quay.io/sighup/prom-rules:3.8_v0.1.0_2.5.0_2.2.0
    pull: always
    depends_on: [ clone ]
    commands:
      - bash katalog/tests/promtool.sh
    when:
      event:
      - push

  - name: examples
    image: quay.io/sighup/furyctl-bats:v0.1.0_1.0.10
    pull: always
    depends_on: [ clone ]
    commands:
      - git config --global url."https://github.com/".insteadOf ssh://git@github.com
      - bats examples/tests.bats
    when:
      event:
      - push

  - name: integration-test
    image: quay.io/sighup/kind:v0.3.0_v1.12.0_1.0.10
    pull: always
    depends_on: [ clone ]
    environment:
      CLUSTER_HOST: docker
      TESTS: katalog/tests/tests.bats
    volumes:
      - name: dockersock
        path: /var/run
    when:
      event:
      - push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
