---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: copper
    image: ruby:2.5
    commands:
      - gem install c66-copper && copper version
      - apt-get update && apt-get install curl -y
      - curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.10/kustomize_1.0.10_linux_amd64 -o /usr/local/bin/kustomize && chmod +x /usr/local/bin/kustomize && kustomize version
      - bash copper.sh
    when:
      event:
      - push
  # - name: prom-rules
  #   image: python:3.7-slim
  #   commands:
  #     - gem install c66-copper
  #     - copper version
  #     - copper check --rules rules.cop --file prometheus-operator/rbac.yml
  #   when:
  #     event:
  #     - push