---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: katalog
    image: python:3
    commands:
      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl
      - curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.10/kustomize_1.0.10_linux_amd64 -o /usr/local/bin/kustomize && chmod +x /usr/local/bin/kustomize && kustomize version
      - pip install -rtest-requirements.txt
      - flake8 --ignore=E501 katalog/tests/test.py
      - bash katalog/tests/k8stest.sh
    when:
      event:
      - push
  - name: prom-rules
    image: alpine:3.8
    commands:
      - apk add --no-cache --update ca-certificates curl bash
      - curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/2.2.0/yq_linux_amd64 && chmod +x /usr/local/bin/yq
      - curl -O -L  https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.linux-amd64.tar.gz && tar -xzvf prometheus-2.5.0.linux-amd64.tar.gz && chmod +x prometheus-2.5.0.linux-amd64/promtool && mv prometheus-2.5.0.linux-amd64/promtool /usr/local/bin/promtool && promtool --version
      - bash katalog/tests/promtest.sh
    when:
      event:
      - push
