bases:
  - git::git@github.com:sighup-io/fury-kubernetes-monitoring.git//alertmanager-operated
  - git::git@github.com:sighup-io/fury-kubernetes-monitoring.git//prometheus-operated

patches:
  - prometheus-alertmanager-externalUrl.yml
