bases:
  - vendor/katalog/monitoring/alertmanager-operated
  - vendor/katalog/monitoring/prometheus-operated
  - vendor/katalog/monitoring/prometheus-operator

patches:
  - prometheus-alertmanager-externalUrl.yml
