# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - dashboards
  - deploy.yml
  - rbac.yml

images:
  - name: grafana/grafana
    newName: reg.sighup.io/sighupio/fury/grafana
    newTag: 7.3.6
  - name: kiwigrid/k8s-sidecar
    newName: reg.sighup.io/sighupio/fury/kiwigrid/k8s-sidecar
    newTag: 1.3.0

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards.yaml

secretGenerator:
  - name: grafana-datasources
    files:
      - prometheus.yaml=prometheus.yaml
