bases:
  - vendor/katalog/monitoring/alertmanager-operated
  - vendor/katalog/monitoring/prometheus-operator

secretGenerator:
- name: alertmanager-main
  commands:
    alertmanager.yaml: "cat alertmanager.yaml"

generatorOptions:
  disableHash: true
