# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

bases:
  - vendor/katalog/monitoring/alertmanager-operated
  - vendor/katalog/monitoring/prometheus-operator

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: alertmanager-main
  behavior: merge
  namespace: monitoring
  files: 
    - alertmanager.yaml=alertmanager.yaml
