bases:
  - vendor/katalog/monitoring/alertmanager-operated
  - vendor/katalog/monitoring/prometheus-operator

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: alertmanager-main
  behavior: merge
  namespace: monitoring
  files: 
    - alertmanager.yaml=alertmanager.yaml
