apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - thanos-compact.yaml
  - servicemonitor.yml

images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.12.2
