---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-compact
  namespace: monitoring
spec:
  endpoints:
    - port: http-query
  selector:
    matchLabels:
      app: thanos-compact
