apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    k8s-app: example-app
spec:
  endpoints:
    - interval: 10s
      port: http
      scheme: http
      path: /metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: example-app
