---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - thanos-store.yaml
  - servicemonitor.yml
  - prometheus-rule.yml

images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.12.2

secretGenerator:
  # description: config + credentials for access to object storage
  # used-by: Prometheus, Thanos Store, Thanos Compact
  - name: thanos-storage
    type: Opaque
    files:
      - config.yaml=thanos-storage-secret.yaml
