---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-store
  namespace: monitoring
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: thanos-store
