# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../katalog/grafana

images:
  - name: registry.sighup.io/fury/grafana
    newName: grafana/grafana
  - name: registry.sighup.io/fury/kiwigrid/k8s-sidecar
    newName: kiwigrid/k8s-sidecar
