bases:
  - git::git@github.com:sighup-io/fury-kubernetes-monitoring.git//prometheus-operated

resources:
  - add-alert.yml

# patches:
#   - add-alert.yml
#   - remove-alert.yml
#   - modify-alert.yml
