apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - thanos-query.yaml
  - servicemonitor.yml
  - prometheus-headless.yml
  - prometheus-rule.yml

images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.12.2

configMapGenerator:
  # description: Discovery config of Prometheus instances to aggregate query
  #   results
  # used-by: Thanos Query
  - name: thanos-query
    files:
      - store-sd.yaml=store-sd.yaml
#secretGenerator:
#  - name: grafana-datasources
#    behavior: replace
#    files:
#      - prometheus.yaml=grafana-prometheus.yaml
