---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: thanos-sidecar
  name: thanos-sidecar
spec:
  clusterIP: None
  selector:
    app: prometheus
  ports:
    - name: grpc
      port: 10901
