---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

generatorOptions:
  labels:
    grafana-sighup-dashboard: default
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard-definitions-x509
    files:
      - x509.json
