apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../thanos
  - ../thanos-components/thanos-store
  - ../thanos-components/thanos-compact

namespace: monitoring

configMapGenerator:
  # description: Discovery config of Prometheus instances to aggregate query
  #   results
  # used-by: Thanos Query
  - name: thanos-query
    behavior: replace
    files:
      - store-sd.yaml=store-sd.yaml
