namespace: monitoring

resources:
  - deploy.yml
  - rbac.yml
  - sm.yml

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: alertmanager-main
  namespace: monitoring
  files: 
    - alertmanager.yaml=alertmanager.yaml
    - alertmanager.tmpl=alertmanager.tmpl
