apiVersion: v1
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: "example.org"
      smtp_from: "support@example.org"
      smtp_require_tls: false
    route:
      group_by: ['alertname', 'cluster', 'service', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'sighup-team'
      routes:
      - match:
          alertname: DeadMansSwitch
        group_wait: 30s
        group_interval: 1m
        repeat_interval: 1m
        receiver: healthchecks
      - match:
        receiver: 'sighup-team'
    receivers:
      - name: 'sighup-team'
        slack_configs:
          - channel: kubernetes-alerts
            api_url: 'https://hooks.slack.com/services/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-'
            send_resolved: true
        email_configs:
          - to: 'support@example.org'
            send_resolved: true
      - name: 'healthchecks'
        webhook_configs:
          - url: 'https://hc-ping.com/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    templates:
      - '/etc/alertmanager/config/*.tmpl'
  alertmanager.tmpl: |-
    {{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver }}{{ end }}
    
    {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification{{ end }}
    
    {{ define "__text" }}{{ range .Alerts }}
    *Alert:* {{ .Labels.alertname }} - `{{ .Labels.severity }}`
    *Description:* {{ .Annotations.message }}
    *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
    *Details:*
    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
    {{ end }}{{ end }}{{ end }}
    
    {{ define "slack.default.title" }}{{ template "__subject" . }}{{ end }}
    {{ define "slack.default.username" }}{{ .CommonLabels.k8s_cluster | toUpper }}{{ end }}
    {{ define "slack.default.fallback" }}{{ template "slack.default.title" . }} | {{ template "slack.default.titlelink" . }}{{ end }}
    {{ define "slack.default.pretext" }}{{ end }}
    {{ define "slack.default.titlelink" }}{{ template "__alertmanagerURL" . }}{{ end }}
    {{ define "slack.default.iconemoji" }}{{ end }}
    {{ define "slack.default.iconurl" }}{{ end }}
    {{ define "slack.default.text" }}{{ template "__text" . }}{{ end }}
    {{ define "slack.default.footer" }}{{ end }}
    
    {{ define "email.default.subject" }}{{ template "__subject" .}} - {{ template "slack.default.username" . }}{{ end }}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
