apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: metrics-server
  annotations:
    certmanager.k8s.io/inject-ca-from: "kube-system/metrics-server-tls"
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    name: metrics-server
    namespace: kube-system
  version: v1beta1
