apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      serviceAccountName: metrics-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64
        imagePullPolicy: Always
        args:
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
        - --metric-resolution=30s
        - --secure-port=8443
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key-file=/certs/tls.key
        ports:
        - name: https
          containerPort: 8443
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: https
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: https
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: certs
        secret:
          secretName: metrics-server-tls
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: metrics-server
